
# Cron Schedules have been converted using UTC Time Zone and may need to be updated for your location
schedules:
- cron: "30 8 * * *" # 
  branches:
    include:
   # - refs/heads/main
    - main
  always: true  
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    fetchDepth: 1
  
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'projectSC'
      ScriptType: 'InlineScript'
      Inline: |
        # You can write your azure powershell scripts inline here. 
        # You can also pass predefined and custom variables to this script using arguments
        Update-Module Az.*
      azurePowerShellVersion: 'LatestVersion'
  - task: AzurePowerShell@5
    displayName: 'Azure PowerShell script: FilePath'
    inputs:
      azureSubscription: 'projectSC'
      ScriptType: 'FilePath'
      ScriptPath: 'Remove-AzDeployment.ps1'
      ScriptArguments: -NumberOfDeploymentsToKeep 1 -SubscriptionIds "f7159c82-8d13-41e3-a967-953d43168392"
      azurePowerShellVersion: 'LatestVersion'
  
  
  