trigger:
  branches:
    include:
      - main

schedules:
  - cron: "30 18 * * *" # Run daily at 18:30 UTC
    displayName: Daily Pipeline Run
    branches:
      include:
        - main
    always: true  

jobs:
- job: CleanupOldDeployments
  displayName: Cleanup Old Deployments
  pool:
    vmImage: windows-latest
  steps:
    - checkout: self
      displayName: Checkout Repository
      fetchDepth: 1

    - task: AzurePowerShell@5
      displayName: Run PowerShell Script
      inputs:
        azureSubscription: 'azdemosc'
        ScriptType: 'FilePath'
        ScriptPath: 'Remove-AzDeployment.ps1'
        ScriptArguments: '-NumberOfDeploymentsToKeep 0 -SubscriptionId "77842199-04f9-46b9-9746-6e981a0db01d" -OutputDirectory "$(Build.ArtifactStagingDirectory)"'
        azurePowerShellVersion: 'LatestVersion'
      continueOnError: true

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: lockDetails
      condition: always()
      displayName: 'Publish lockDetails.json'
